import { Platform, StyleSheet } from "react-native";
import { Theme } from "./colors";

export function createStyles(theme: Theme) {
  const isDark = theme.background === "#060C1A";

  const shadow = {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  };

  const shadowStrong = {
    shadowColor: "#060C1A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.20,
    shadowRadius: 24,
    elevation: 8,
  };

  const shadowColored = {
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 6,
  };

  const shadowCardDark = {
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 5,
  };

  return StyleSheet.create({
    safeArea: {
      backgroundColor: theme.background,
      flex: 1,
    },
    authSafeArea: {
      backgroundColor: theme.navy,
      flex: 1,
    },
    keyboardRoot: {
      flex: 1,
    },
    appShell: {
      backgroundColor: theme.background,
      flex: 1,
    },
    authShell: {
      backgroundColor: theme.navy,
      flex: 1,
      justifyContent: "center",
      padding: 24,
    },
    splashContent: {
      gap: 16,
    },
    logoOrb: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: theme.sky,
      borderRadius: 16,
      height: 72,
      justifyContent: "center",
      width: 72,
    },
    authTitle: {
      color: "#ffffff",
      fontSize: 32, fontWeight: "800",
      textAlign: "center",
    },
    authSubtitle: {
      color: "#BFDBFE",
      fontSize: 18,
      fontWeight: "800",
      textAlign: "center",
    },
    illustrationCard: {
      alignItems: "center",
      backgroundColor: "rgba(255,255,255,0.08)",
      borderColor: "rgba(255,255,255,0.14)",
      borderRadius: 16,
      borderWidth: 1,
      flexDirection: "row",
      justifyContent: "center",
      padding: 16,
    },
    illustrationNode: {
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderRadius: 16,
      height: 58,
      justifyContent: "center",
      width: 58,
    },
    illustrationLine: {
      backgroundColor: "rgba(255,255,255,0.26)",
      height: 2,
      width: 34,
    },
    authCard: {
      ...shadow,
      backgroundColor: theme.card,
      borderRadius: 16,
      gap: 16,
      padding: 20,
    },
    authCardTitle: {
      color: theme.text,
      fontSize: 24, fontWeight: "700",
    },
    authCardText: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 21,
    },
    roleGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    roleChip: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      flexBasis: "48%",
      padding: 8,
    },
    roleChipPressed: {
      transform: [{ scale: 0.98 }],
      shadowColor: theme.sky,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
    },
    roleChipActive: {
      backgroundColor: theme.skySoft,
      borderColor: theme.sky,
    },
    roleChipLabel: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "800",
      marginBottom: 4,
    },
    roleChipLabelActive: {
      color: theme.skyDark,
    },
    roleChipText: {
      color: theme.muted,
      fontSize: 11,
      lineHeight: 16,
    },
    roleMetaRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      marginTop: 8,
    },
    roleMetaText: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: "800",
    },
    roleMetaTextActive: {
      color: theme.skyDark,
    },
    stepHeader: {
      gap: 8,
    },
    stepPillRow: {
      flexDirection: "row",
      gap: 8,
    },
    stepPill: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    stepPillActive: {
      backgroundColor: theme.skySoft,
      borderColor: theme.sky,
    },
    stepPillText: {
      color: theme.muted,
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    stepPillTextActive: {
      color: theme.skyDark,
    },
    badgeAccent: {
      alignSelf: "flex-start",
      backgroundColor: "rgba(56, 189, 248, 0.12)",
      borderColor: "rgba(56, 189, 248, 0.28)",
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    badgeAccentText: {
      color: theme.sky,
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    infoBanner: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      flexDirection: "row",
      gap: 8,
      padding: 8,
    },
    infoBannerText: {
      color: theme.text,
      flex: 1,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 18,
    },
    topRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 16,
    },
    compactHeaderRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 16,
      justifyContent: "space-between",
      marginBottom: 8,
    },
    compactRoleLabel: {
      color: theme.text,
      fontSize: 16, fontWeight: "600",
    },
    backLink: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
    },
    selectedRoleCard: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      gap: 8,
      padding: 16,
    },
    selectedRoleLabel: {
      color: theme.text,
      fontSize: 16, fontWeight: "600",
    },
    selectedRoleDescription: {
      color: theme.skyDark,
      fontSize: 13,
      fontWeight: "800",
    },
    inputGroup: {
      gap: 8,
    },
    labelText: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    inputField: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      color: theme.text,
      fontSize: 15,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    errorText: {
      color: theme.rose,
      fontSize: 12,
      fontWeight: "700",
    },
    appHeader: {
      backgroundColor: theme.background,
      borderBottomColor: theme.line,
      borderBottomWidth: 1,
      gap: 16,
      padding: 16,
      paddingBottom: 14,
    },
    headerProfileRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 16,
    },
    headerBackAction: {
      alignItems: "center",
      justifyContent: "center",
      marginRight: 6,
      padding: 4,
    },
    avatar: {
      alignItems: "center",
      backgroundColor: theme.sky,
      borderRadius: 16,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    avatarText: {
      color: "#ffffff",
      fontSize: 16, fontWeight: "600",
    },
    greeting: {
      color: theme.text,
      fontSize: 18, fontWeight: "600",
    },
    headerSubline: {
      color: theme.muted,
      fontSize: 13,
      marginTop: 2,
    },
    headerIconButton: {
      alignItems: "center",
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    unreadDot: {
      alignItems: "center",
      backgroundColor: theme.rose,
      borderRadius: 999,
      minWidth: 18,
      paddingHorizontal: 4,
      position: "absolute",
      right: -4,
      top: -4,
    },
    unreadText: {
      color: "#ffffff",
      fontSize: 10,
      fontWeight: "900",
    },
    screenTitle: {
      color: theme.text,
      fontSize: 24, fontWeight: "700",
    },
    scrollContent: {
      gap: 16,
      padding: 16,
      paddingBottom: 118,
    },
    stack: {
      gap: 16,
    },
    stackSmall: {
      gap: 9,
    },
    rowStart: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
    },
    rowBetween: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
    },
    flex1: {
      flex: 1,
    },
    card: {
      ...(isDark ? shadowCardDark : shadow),
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      gap: 12,
      padding: 16,
    },
    cardStrong: {
      ...shadowStrong,
      backgroundColor: theme.cardElevated,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      gap: 12,
      padding: 16,
    },
    tone_success: {
      borderColor: theme.emeraldSoft,
    },
    tone_warning: {
      borderColor: theme.amberSoft,
    },
    tone_critical: {
      borderColor: theme.roseSoft,
    },
    tone_info: {
      borderColor: theme.skySoft,
    },
    tone_blocked: {
      borderColor: theme.blockedSoft,
    },
    aiCard: {
      ...shadowStrong,
      backgroundColor: theme.cardElevated,
      borderColor: theme.skySoft,
      borderRadius: 16,
      borderWidth: 1,
      gap: 16,
      overflow: "hidden",
      padding: 16,
      paddingBottom: 14,
    },
    aiAvatar: {
      alignItems: "center",
      backgroundColor: theme.sky,
      borderRadius: 16,
      height: 46,
      justifyContent: "center",
      width: 46,
    },
    miniAiAvatar: {
      alignItems: "center",
      backgroundColor: theme.sky,
      borderRadius: 10,
      height: 28,
      justifyContent: "center",
      width: 28,
    },
    liveBadge: {
      backgroundColor: theme.emeraldSoft,
      borderRadius: 999,
      color: theme.emerald,
      fontSize: 12,
      fontWeight: "900",
      overflow: "hidden",
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    heroTitle: {
      color: theme.text,
      fontSize: 24, fontWeight: "700",
    },
    heroText: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 22,
    },
    statGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 16,
    },
    statValue: {
      color: theme.text,
      fontSize: 24, fontWeight: "700",
    },
    actionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    actionCard: {
      ...(isDark ? shadowCardDark : shadow),
      alignItems: "flex-start",
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      gap: 8,
      minHeight: 104,
      padding: 16,
      width: "48%",
    },
    actionIcon: {
      alignItems: "center",
      backgroundColor: theme.skySoft,
      borderRadius: 12,
      height: 40,
      justifyContent: "center",
      width: 40,
    },
    actionLabel: {
      color: theme.text,
      fontSize: 16, fontWeight: "600",
      lineHeight: 19,
    },
    sectionHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 4,
    },
    sectionIcon: {
      alignItems: "center",
      backgroundColor: theme.skySoft,
      borderRadius: 11,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 18, fontWeight: "600",
    },
    cardTitle: {
      color: theme.text,
      fontSize: 16, fontWeight: "600",
      lineHeight: 22,
    },
    bodyText: {
      color: theme.muted,
      fontSize: 14,
      lineHeight: 21,
    },
    bodyStrong: {
      color: theme.text,
      fontSize: 16, fontWeight: "600",
      lineHeight: 20,
    },
    mutedText: {
      color: theme.muted,
      fontSize: 13,
      lineHeight: 19,
    },
    metaText: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: "800",
    },
    microcopy: {
      color: theme.muted,
      flex: 1,
      fontSize: 12,
      lineHeight: 18,
    },
    linkText: {
      color: theme.sky,
      fontSize: 14, fontWeight: "600",
    },
    primaryButton: {
      ...shadowColored,
      alignItems: "center",
      backgroundColor: theme.sky,
      borderRadius: 12,
      flexDirection: "row",
      gap: 8,
      justifyContent: "center",
      minHeight: 48,
      minWidth: 44,
      paddingHorizontal: 16,
    },
    primaryButtonText: {
      color: "#ffffff",
      fontSize: 16, fontWeight: "600",
    },
    secondaryButton: {
      alignItems: "center",
      backgroundColor: theme.skySoft,
      borderRadius: 12,
      flexDirection: "row",
      gap: 8,
      justifyContent: "center",
      minHeight: 48,
      minWidth: 44,
      paddingHorizontal: 16,
    },
    secondaryButtonText: {
      color: theme.skyDark,
      fontSize: 16, fontWeight: "600",
    },
    iconButton: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    chipWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    horizontalRail: {
      flexDirection: "row",
      gap: 8,
      paddingRight: 18,
    },
    chip: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    chipActive: {
      backgroundColor: theme.skySoft,
      borderColor: theme.sky,
    },
    chipText: {
      color: theme.text,
      fontSize: 12,
      fontWeight: "800",
    },
    badge: {
      alignSelf: "flex-start",
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    badgeText: {
      fontSize: 11,
      fontWeight: "900",
    },
    voiceRow: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      flexDirection: "row",
      gap: 8,
      padding: 8,
    },
    progressTrack: {
      backgroundColor: theme.line,
      borderRadius: 999,
      height: 9,
      overflow: "hidden",
    },
    progressFill: {
      backgroundColor: theme.emerald,
      borderRadius: 999,
      height: "100%",
    },
    progressValue: {
      color: theme.text,
      fontSize: 28,
      fontWeight: "900",
    },
    progressValueSmall: {
      color: theme.sky,
      fontSize: 18, fontWeight: "600",
    },
    documentRow: {
      ...(isDark ? shadowCardDark : shadow),
      alignItems: "center",
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderRadius: 16,
      borderWidth: 1,
      flexDirection: "row",
      gap: 16,
      padding: 16,
    },
    documentIcon: {
      alignItems: "center",
      backgroundColor: theme.skySoft,
      borderRadius: 12,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    chatBubble: {
      borderRadius: 12,
      gap: 8,
      padding: 16,
    },
    chatBubbleAi: {
      backgroundColor: theme.surfaceAlt,
      borderTopLeftRadius: 4,
      marginRight: 40,
    },
    chatBubbleEmployee: {
      alignSelf: "flex-end",
      backgroundColor: theme.sky,
      borderTopRightRadius: 4,
      marginLeft: 40,
    },
    employeeMessageText: {
      color: "#ffffff",
      fontSize: 14,
      fontWeight: "700",
      lineHeight: 21,
    },
    actionButtonRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    inlineAction: {
      backgroundColor: theme.skySoft,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 7,
    },
    inlineActionText: {
      color: theme.skyDark,
      fontSize: 12,
      fontWeight: "900",
    },
    chatInput: {
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      color: theme.text,
      minHeight: 92,
      padding: 16,
      textAlignVertical: "top",
    },
    sendButton: {
      alignItems: "center",
      backgroundColor: theme.emerald,
      borderRadius: 12,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    typingDot: {
      backgroundColor: theme.sky,
      borderRadius: 999,
      height: 8,
      width: 8,
    },
    securityNote: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      flexDirection: "row",
      gap: 8,
      padding: 8,
    },
    skeletonBlock: {
      gap: 8,
      width: "100%",
    },
    skeletonLineLarge: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 999,
      height: 14,
      width: "86%",
    },
    skeletonLine: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 999,
      height: 12,
      width: "70%",
    },
    skeletonLineShort: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 999,
      height: 12,
      width: "44%",
    },
    emptyState: {
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
    },
    emptyIcon: {
      alignItems: "center",
      backgroundColor: theme.skySoft,
      borderRadius: 16,
      height: 54,
      justifyContent: "center",
      width: 54,
    },
    taskList: {
      gap: 8,
      marginTop: 8,
    },
    taskRow: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      flexDirection: "row",
      gap: 8,
      padding: 11,
    },
    statusIcon: {
      alignItems: "center",
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    successMedal: {
      alignItems: "center",
      backgroundColor: theme.emerald,
      borderRadius: 16,
      height: 46,
      justifyContent: "center",
      width: 46,
    },
    notificationStripe: {
      borderRadius: 999,
      height: 56,
      width: 5,
    },
    smallUnreadDot: {
      backgroundColor: theme.rose,
      borderRadius: 999,
      height: 9,
      width: 9,
    },
    metaRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      marginTop: 8,
    },
    swipeAction: {
      alignItems: "center",
      alignSelf: "flex-start",
      flexDirection: "row",
      gap: 8,
      marginTop: 2,
    },
    profileHero: {
      alignItems: "center",
      gap: 8,
    },
    profileAvatar: {
      alignItems: "center",
      backgroundColor: theme.emerald,
      borderRadius: 16,
      height: 72,
      justifyContent: "center",
      width: 72,
    },
    profileAvatarText: {
      color: "#ffffff",
      fontSize: 23,
      fontWeight: "900",
    },
    profileName: {
      color: theme.text,
      fontSize: 22,
      fontWeight: "900",
    },
    infoGrid: {
      gap: 8,
      marginTop: 16,
    },
    kpiCard: {
      flex: 1,
    },
    infoRow: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      gap: 3,
      padding: 16,
    },
    settingRow: {
      alignItems: "center",
      borderBottomColor: theme.line,
      borderBottomWidth: 1,
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 54,
    },
    inlineToggle: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
    },
    dropdownButton: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
    },
    dropdownMenu: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      gap: 2,
      marginBottom: 8,
      padding: 8,
    },
    dropdownItem: {
      padding: 8,
    },
    privacyButton: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      paddingVertical: 16,
    },
    inputCard: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: "row",
      gap: 8,
      minHeight: 58,
      padding: 16,
    },
    inputText: {
      color: theme.text,
      fontSize: 15,
      fontWeight: "800",
      marginTop: 3,
    },
    otpRow: {
      flexDirection: "row",
      gap: 8,
      justifyContent: "center",
    },
    otpCell: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderColor: theme.sky,
      borderRadius: 12,
      borderWidth: 1,
      height: 58,
      justifyContent: "center",
      width: 58,
    },
    otpDigit: {
      color: theme.text,
      fontSize: 24, fontWeight: "700",
    },
    validationList: {
      gap: 8,
    },
    checkRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 8,
    },
    modalBackdrop: {
      backgroundColor: isDark ? "rgba(0,0,0,0.62)" : "rgba(0,0,0,0.42)",
      flex: 1,
      justifyContent: "flex-end",
    },
    modalSheet: {
      backgroundColor: isDark ? theme.cardElevated : theme.background,
      borderColor: isDark ? "rgba(59,130,246,0.18)" : "transparent",
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderTopWidth: isDark ? 1 : 0,
      borderLeftWidth: isDark ? 1 : 0,
      borderRightWidth: isDark ? 1 : 0,
      gap: 16,
      maxHeight: "88%",
      padding: 16,
    },
    modalTitle: {
      color: theme.text,
      fontSize: 21,
      fontWeight: "900",
    },
    modalScroll: {
      maxHeight: 470,
    },
    modalActions: {
      gap: 8,
    },
    stepper: {
      flexDirection: "row",
      gap: 8,
    },
    stepItem: {
      alignItems: "center",
      flex: 1,
      gap: 4,
    },
    stepCircle: {
      alignItems: "center",
      backgroundColor: theme.surfaceAlt,
      borderRadius: 999,
      height: 28,
      justifyContent: "center",
      width: 28,
    },
    stepCircleText: {
      color: theme.muted,
      fontSize: 12,
      fontWeight: "900",
    },
    stepLabel: {
      color: theme.muted,
      fontSize: 10,
      fontWeight: "800",
      textAlign: "center",
    },
    fieldBlock: {
      gap: 8,
    },
    fieldLabel: {
      color: theme.text,
      fontSize: 14, fontWeight: "600",
    },
    fieldInput: {
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderRadius: 12,
      borderWidth: 1,
      color: theme.text,
      minHeight: 48,
      paddingHorizontal: 16,
    },
    fieldInputDisabled: {
      opacity: 0.72,
    },
    timelineRow: {
      flexDirection: "row",
      gap: 8,
      minHeight: 58,
    },
    timelineTrack: {
      alignItems: "center",
      width: 18,
    },
    timelineDot: {
      borderRadius: 999,
      height: 12,
      marginTop: 3,
      width: 12,
    },
    timelineLine: {
      backgroundColor: theme.line,
      flex: 1,
      marginTop: 4,
      width: 2,
    },
    bottomNav: {
      backgroundColor: theme.card,
      borderColor: theme.line,
      borderTopWidth: 1,
      bottom: 0,
      flexDirection: "row",
      gap: 4,
      left: 0,
      paddingBottom: Platform.OS === "ios" ? 18 : 10,
      paddingHorizontal: 8,
      paddingTop: 8,
      position: "absolute",
      right: 0,
    },
    bottomTab: {
      alignItems: "center",
      borderRadius: 12,
      flex: 1,
      gap: 4,
      justifyContent: "center",
      minHeight: 58,
      paddingHorizontal: 2,
    },
    bottomTabActive: {
      backgroundColor: theme.skySoft,
    },
    bottomTabText: {
      color: theme.muted,
      fontSize: 10,
      fontWeight: "800",
      textAlign: "center",
    },
    bottomTabTextActive: {
      color: theme.sky,
    },
    toast: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: theme.navy,
      borderRadius: 999,
      bottom: 94,
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
      position: "absolute",
    },
    toastText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "900",
    },
  });
}
